### ISSUE TITLE
Problem with MPI version of worker sample

### ISSUE THREAD

**Issue by msurkovsky** [spirali/kaira#21]
It seems that MPI version of worker sample has stopped working. It lookes as it is freezed just after the start.

**Comment by spirali** [comment]
How many processes are you using? ("Workers" do not work for one process)

**Comment by msurkovsky** [comment]
4; mpirun -np 4 ./workers_mpi -pSize=10 -pLIMIT=120. It should be the default setting.

**Comment by msurkovsky** [comment]
Ok, I've just find out what's the problem. My laptop as well as my office computer uses *openmpi* version by default and this makes the problem. When I've tried it at home it's worked; the only difference is a set version of mpi.

**Comment by spirali** [comment]
As I understand, it is not a Kaira problem, hence I am closing the issue. If you think that it is not true, reopen it.

**Comment by msurkovsky** [comment]
I'm not sure about that. I don't understand why it is depended on a chosen version of MPI?  Moreover, in the case when other applications like ```heatflow``` does not suffer by this problem.
