### ISSUE TITLE
Remove methods for tracing values within transitions

### ISSUE THREAD

**Issue by msurkovsky** [spirali/kaira#3]
Context still provides methods for tracing values within transitions. They should be removed.

**Comment by spirali** [comment]
I am not 100% sure if some examples still do not used it (aco?). Or if there is still some code in gui that supports it.

**Comment by msurkovsky** [comment]
As far as I know, there is no example which uses tracing function directly within transition. Moreover, current extensions don not support this. At least, it should be marked as deprecated functionality and deleted after solving special tracing places -- releasing data.

**Comment by spirali** [comment]
Ok, I have removed C++ API, but but I have left the code in Gui to load old tracelogs. We can removed it in a future version.
